trigger:
- main

pool: Default

stages:
- stage: CI
  jobs:
  - job: CIWork
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          echo "Do CI work"
      displayName: 'Run CI work script'
