trigger:
- main

pool: pool

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd).$(Rev:r)

stages:
- stage: CI
  jobs:
  - job: Build1
    steps:
      - script: sudo cp index.html /var/www/html