trigger:
- main

pool: pool

name: $(TeamProject)_$(Date:yyyyMMdd)_$(Hours).$(Minutes).$(Seconds).$(Rev:r)

variables:
  imageName: 'calculator-image'
  DOCKER_BUILDKIT: 1

stages:
- stage: Build
  jobs:
  - job: DockerImage
    steps:
      - task: Docker@2
        displayName: Build an image
        inputs:
          repository: $(imageName)
          command: build
          Dockerfile: ./Dockerfile
