trigger:
- main

pool: pool

name: $(TeamProject)_$(Date:yyyyMMdd)_$(Hours).$(Minutes).$(Seconds).$(Rev:r)

stages:
- stage: Build
  jobs:
  - job: DockerImage
    steps:
      - script: |
          echo "Building the Docker image..."
          sudo docker build -t calculator-image .
      - script: |
          echo "Running the Docker container..."
          sudo docker run -dit -p 8080:80 calculator-image
