trigger:
- main

pool: pool

name: $(TeamProject)_$(Date:yyyy/MM/dd)_$(Hours):$(Minutes):$(Seconds).$(Rev:r)

stages:
- stage: CI
  jobs:
  - job: Build1
    steps:
      - script: sudo cp index.html /var/www/html