trigger:
- main

pool:
  name: pool

variables:
  ImageName: 'caluculator-image-$(Build.BuildId)'
  version: $[format('{0:ddMMyyyy}', pipeline.startTime)]

name: $(TeamProject)_$(Date:yyyyMMdd)_$(Hours).$(Minutes).$(Seconds).$(Rev:r)

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: DockerImage
    displayName: Build and push Docker image
    steps:
     - script: |
        echo "this is the docker image: $(ImageName)"
     - task: Docker@2
       displayName: Build an image
       inputs:
         repository: $(ImageName)
         command: build
         Dockerfile: ./Dockerfile
     - script: |
        docker images $(ImageName)
     - script: |
        if [ $? -eq 0 ]; then
          docker tag $(ImageName) udaykumarreddy995/$(ImageName)
        else
          echo "Failed to find the image: $(ImageName)"
          exit 1
        fi
