trigger:
- main

pool: pool

name: $(TeamProject)_$(Date:yyyyMMdd)_$(Hours).$(Minutes).$(Seconds).$(Rev:r)

stages:
- stage: Build
  jobs:
  - job: test
    steps:
      - script: sudo cp index.html /var/www/html
  - job: Dockerimage
    steps:
      - script: 
          docker build -t calculator-image .
          docker run -dit -p 80:80 calculator-image
