trigger:
- main

pool: pool

name: $(Build.DefinitionName)_$(Build.DefinitionVersion)_$(Build.RequestedFor)_$(Build.BuildId)_$(My.Variable)

stages:
- stage: CI
  jobs:
  - job: Build1
    steps:
      - script: sudo cp index.html /var/www/html