trigger:
- main

pool: pool

stages:
- stage: CI
  jobs:
  - job: Build
    steps:
    - script: echo Hello world!
      displayName: Say hello
  - job: secondwork
    steps:
    - script: echo say hello again
      displayName: Say hello    

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'