trigger:
- main

pool: pool

name: $(TeamProject)_$(Date:yyyyMMdd)_$(Hours).$(Minutes).$(Seconds).$(Rev:r)

stages:
- stage: CI
  jobs:
  - job: test the calculator app with ubuntu server
    steps:
      - script: sudo cp index.html /var/www/html
  - job: Build the docker image
    steps:
      - script: 
          docker build -t calculator-image .
          docker run -dit -p 80:80 calculator-image
