trigger:
- main

pool: pool

variables: 
  MyRunNumber: '1.0.0-CI+$(Build.BuildNumber)'

name: $(Build.BuildNumber)

stages:
- stage: CI
  jobs:
  - job: Build1
    steps:
      - script: sudo cp index.html /var/www/html