name: $(TeamProject)_$(Date:yyyyMMdd)_$(Hours).$(Minutes).$(Seconds).$(Rev:r)

trigger:
- main

pool:
  name: pool

variables:
  ImageName: 'caluculator-image'
  azureSubscription: 'Devops Subscription (4e47bc78-be26-4e40-8697-9cacd49ce169)'
  appName: 'demowebapp490970'
  containerRegistry: 'demoapp490970'
  imageRepository: 'caluculator-image'
  dockerRegistryServiceConnection: 'demoapp490970 service connection'
  dockerfilePath: './Dockerfile'
  tag: '$(Build.BuildId)'


stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: DockerImage
    displayName: Build and push Docker image
    steps:
     - task: Docker@2
       displayName: Build and publish image to Azure Container Registry
       inputs:
         repository: $(ImageName)
         command: buildAndPush
         Dockerfile: $(dockerfilePath)
         containerRegistry: $(dockerRegistryServiceConnection)
         tags: |
          $(tag)
     - task: AzureWebAppContainer@1
       displayName: 'Azure Web App on Container Deploy'
       inputs:
         azureSubscription: $(azureSubscription)
         appName: $(appName)
         containers: $(containerRegistry)/$(imageRepository):$(tag)    
    # - script: |
    #    docker images $(ImageName)
    #     docker tag $(ImageName):$(Build.BuildId) demoapp490970.azurecr.io/$(ImageName):$(Build.BuildId)
