name: $(TeamProject)_$(Date:yyyyMMdd)_$(Hours).$(Minutes).$(Seconds).$(Rev:r)

trigger:
- main

pool:
  name: pool

variables:
  azureSubscription: 'Devops Subscription'
  appName: 'demowebapp490970'
  containerRegistry: 'demoapp490970.azurecr.io'
  imageRepository: 'calculator-image'
  dockerRegistryServiceConnection: 'demoapp490970 service connection'
  dockerfilePath: './Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: DockerImage
    displayName: Build and push Docker image
    steps:
     - task: Docker@2
       displayName: Build and publish image to Azure Container Registry
       inputs:
         repository: $(containerRegistry)/$(imageRepository)
         command: buildAndPush
         Dockerfile: $(dockerfilePath)
         containerRegistry: $(dockerRegistryServiceConnection)
         tags: |
          $(tag)
     - task: AzureWebAppContainer@1
       displayName: 'Azure Web App on Container Deploy'
       inputs:
         azureSubscription: $(azureSubscription)
         appName: $(appName)
         containers: $(containerRegistry)/$(imageRepository):$(tag)    
