trigger:
- main

pool: pool

variables:
  imageName: 'my-nginx-image'
  version: date "+%Y-%m-%d-%H:%M:%S"

name: $(TeamProject)_$(Date:yyyyMMdd)_$(Hours).$(Minutes).$(Seconds).$(Rev:r)

stages:
- stage: Build
  jobs:
  - job: DockerImage
    steps:
      - script: |
          echo "Building the $(imageName)..."
          sudo docker build -t $(imageName):$(version) .
      - script: |
          echo "Running the Docker container..."
          sudo docker run -dit -p 81:80 $(imageName):$(version)
