trigger:
- main

pool:
  name: pool

variables:
  imageName: 'caluculator-image:$(Build.BuildId)'
  version: $[format('{0:ddMMyyyy}', pipeline.startTime)]

name: $(TeamProject)_$(Date:yyyyMMdd)_$(Hours).$(Minutes).$(Seconds).$(Rev:r)

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: DockerImage
    displayName: Build and push Docker image
    steps:
    - script: |
        echo "Building the Docker image with sudo..."
        sudo docker build -t $(ImageName) .
        sudo docker run -dit -p 8080:80 $(ImageName)
      
