trigger:
- main

pool: pool

stages:
- stage: CI
  jobs:
  - job: CIWork
    steps:
    - script: echo Hello world!
      displayName: Say hello

- stage: CD
  jobs:
  - job: CDWork
    steps:
    - script: echo Thank you!
      displayName: Say bye