name: Cron Workflow
on:
  schedule:
    - cron: '* * * * *' # Run every minute
    
  workflow_dispatch:    
  
jobs:
  cron_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: uday # Replace 'uday' with your specific branch name
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run cron job script
        run: python cron_script.py
