name: Test Cron Job

on:
  schedule:
    - cron: '* * * * *'

jobs:

  cron-job:
    name: Cron Job
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup PowerShell
      uses: actions/setup-powershell@v3
      
    - name: Run PowerShell Script
      run: |
        $currentTime = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        Write-Host "Running PowerShell script at $currentTime (IST)"
        
        # Sample PowerShell commands
        Get-Process | Sort-Object CPU -Descending | Select-Object -First 5
        
        Write-Host "PowerShell script completed."
      env:
        TZ: Asia/Kolkata
