apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: test-container
            image: mcr.microsoft.com/powershell:lts-nanoserver-1809
            command:
            - pwsh
            - -c
            - |
              Write-Host "Running PowerShell script at $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
              
              # Sample PowerShell commands
              Get-Process | Sort-Object CPU -Descending | Select-Object -First 5
              
              Write-Host "PowerShell script completed."
          restartPolicy: OnFailure
