name: Test Cron Job

on:
  schedule:
    - cron: '*/5 * * * *' # Run every minute

jobs:
  cron_job:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: uday

      - name: Set up PowerShell
        uses: actions/setup-powershell@v2
        with:
          pwsh-version: '7.x'

      - name: Run cron job script
        run: |
          Write-Host "This is a sample cron job script"
          Write-Host "Another line of output"
          Write-Host "Additional output line"
