name: Display GCP Resources

on:
  workflow_dispatch: 

jobs:

  display-resources:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - run: | 
        gcloud services list
