name: Python-cronjob
on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  python-job:
    runs-on: ubuntu-latest

    steps:
    - name: repo
      uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run python script
      run: python hello.py
    
