name: Run Script on Specific Branch

on:
  schedule:
    - cron: '*/5 * * * *' # Run every 5 minutes

jobs:
  run-script:
    name: Run Script on Test Branch
    runs-on: ubuntu-latest
    
    # Checkout the test branch
    steps:
    - uses: actions/checkout@v3
      with:
        ref: test # Specify the branch you want to check out

    # Your script steps here
    - name: Run Script
      run: |
        # Your script commands
        # Example: Run a Python script
      
